### ISSUE TITLE
[v2] Gulp version error with kitchen sink

### ISSUE THREAD

**Issue by scriptPilot** [framework7io/framework7-vue#262]
What I did
- Switched to v2 branch
- Downloaded repo
- Run npm install
- Run npm run dev

What I got

```
Denniss-iMac:Framework7-Vue-2 dennis$ npm run dev

> framework7-vue@2.0.0-beta.3 dev /Users/dennis/Documents/Framework7-Vue-2
> cross-env NODE_ENV=development gulp ks && cross-env NODE_ENV=development gulp server

/Users/dennis/Documents/Framework7-Vue-2/node_modules/gulp/node_modules/semver/semver.js:295
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: https://registry.npmjs.org/gulp/-/gulp-3.9.1.tgz
    at new SemVer (/Users/dennis/Documents/Framework7-Vue-2/node_modules/gulp/node_modules/semver/semver.js:295:11)
    at compare (/Users/dennis/Documents/Framework7-Vue-2/node_modules/gulp/node_modules/semver/semver.js:571:10)
    at Function.gt (/Users/dennis/Documents/Framework7-Vue-2/node_modules/gulp/node_modules/semver/semver.js:600:10)
    at Liftoff.handleArguments (/Users/dennis/Documents/Framework7-Vue-2/node_modules/gulp/bin/gulp.js:99:14)
    at Liftoff.<anonymous> (/Users/dennis/Documents/Framework7-Vue-2/node_modules/liftoff/index.js:198:16)
    at module.exports (/Users/dennis/Documents/Framework7-Vue-2/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/Users/dennis/Documents/Framework7-Vue-2/node_modules/liftoff/index.js:190:9)
    at /Users/dennis/Documents/Framework7-Vue-2/node_modules/liftoff/index.js:164:9
    at /Users/dennis/Documents/Framework7-Vue-2/node_modules/v8flags/index.js:110:14
    at /Users/dennis/Documents/Framework7-Vue-2/node_modules/v8flags/index.js:38:12
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! framework7-vue@2.0.0-beta.3 dev: `cross-env NODE_ENV=development gulp ks && cross-env NODE_ENV=development gulp server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the framework7-vue@2.0.0-beta.3 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dennis/.npm/_logs/2017-10-24T21_44_49_332Z-debug.log

```

**Comment by nolimits4web** [comment]
Closing as not relevant anymore
